name: Linux - RustDesk

on:
  workflow_dispatch:

jobs:
  linux:
    name: Linux - RustDesk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl python3 python3-pip \
            libxdo3 libxcb-shape0 libva-drm2 libva-x11-2 \
            libvdpau1 libgstreamer-plugins-base1.0-0 \
            libappindicator3-1 gstreamer1.0-pipewire

      - name: Download RustDesk
        run: |
          curl -L -o rustdesk.deb "https://github.com/rustdesk/rustdesk/releases/download/1.2.1/rustdesk-1.2.1-x86_64.deb"
          sudo dpkg -i rustdesk.deb || sudo apt-get install -f

      - name: Log In To AnyDesk
        run: python3 login.py

      - name: Wait for 4 hours
        run: sleep 14400  # 14400 seconds = 4 hours
