name: RustDesk Installation and Login

on:
  workflow_dispatch:

jobs:
  build:
    name: Install RustDesk
    runs-on: ubuntu-latest

    steps:
      - name: Downloading RustDesk
        run: |
          # Download the RustDesk .deb package
          curl -LO "https://github.com/rustdesk/rustdesk/releases/download/1.2.1/rustdesk-1.2.1-amd64.deb"  # Replace with actual version if needed

      - name: Install RustDesk on Ubuntu
        run: |
          sudo apt update
          sudo apt install -fy ./rustdesk-1.2.1-amd64.deb  # Install RustDesk

      - name: Display Login Credentials
        run: |
          echo "RustDesk installed successfully!"
          echo "To log in, use the following credentials:"
          echo "ID: 123456"  # Replace with actual ID
          echo "Password: your_password"  # Replace with actual password
          
      - name: Start RustDesk
        run: |
          rustdesk &  # Start RustDesk in the background

      - name: Wait for 4 hours
        run: |
          sleep 14400  # 14400 seconds = 4 hours
