name: Linux - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Downloading & Installing Essentials
        run: |
          curl -L -o login.py https://www.dropbox.com/scl/fi/az5jzhpuiylnw7yqw9du5/login.py?rlkey=1qjxif8fu35dh0v77nagv2ihh&dl=0
          curl -L -o loop.sh https://www.dropbox.com/scl/fi/vji7ekyslpbovokpqeay3/loop.bat?rlkey=876nfzm3qdmyqhc1jckgqjcld&dl=0
          curl -L -o show.sh https://www.dropbox.com/scl/fi/cwbwdo2n3tt8rbqmugc6h/show.bat?rlkey=41m0ds12mg6e28giib3zqlf6w&dl=0
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install pyautogui psutil --quiet
          curl -L -o rustdesk.deb https://github.com/rustdesk/rustdesk/releases/download/1.2.1/rustdesk-1.2.1-x86_64.deb
          sudo dpkg -i rustdesk.deb
          rm rustdesk.deb

      - name: Log In To AnyDesk
        run: |
          echo "Logging in to AnyDesk..."
          # Assuming you have a method to log in to AnyDesk on Linux
          anydesk &  # Starts AnyDesk if installed

      - name: Wait for 4 hours
        run: |
          sleep 14400  # 14400 seconds = 4 hours
